// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'bluePrimary': string;
  'container': string;
  'fontPrimary': string;
  'greyPrimary': string;
  'greyTertiary': string;
  'mark': string;
  'score': string;
}
export const cssExports: CssExports;
export default cssExports;
