// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bluePrimary': string;
  'button': string;
  'container': string;
  'fontPrimary': string;
  'greyTertiary': string;
}
export const cssExports: CssExports;
export default cssExports;
