// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bluePrimary': string;
  'board': string;
  'container': string;
  'flip': string;
  'greySecondary': string;
  'innerContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
