// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'blueSecondary': string;
  'bottom': string;
  'cell': string;
  'greyPrimary': string;
  'left': string;
  'right': string;
  'symbolBlack': string;
  'symbolWhite': string;
  'top': string;
}
export const cssExports: CssExports;
export default cssExports;
