// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  container: string;
  fontPrimary: string;
  greyPrimary: string;
  icon: string;
}
export const cssExports: CssExports;
export default cssExports;
