// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'fontPrimary': string;
  'greyQuaternary': string;
  'header': string;
}
export const cssExports: CssExports;
export default cssExports;
